# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Watcher Noob

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Installing OS dependencies
      run: |
        sudo apt-get install libxml2-dev libxslt-dev python-dev python3-testresources
    - name: Importing creadiatels
      env:
        SITE_URL: https://service7.rumbletalk.net/Eo3h031D/
        LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
        LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        BOT_API_URL: https://api.telegram.org/bot
      run: |
        touch .env
        echo SITE_URL=$SITE_URL >> .env
        echo LOGIN_USERNAME=$LOGIN_USERNAME >> .env
        echo LOGIN_PASSWORD=$LOGIN_PASSWORD >> .env
        echo BOT_TOKEN=$BOT_TOKEN >> .env
        echo CHAT_ID=$CHAT_ID >> .env
        echo BOT_API_URL=$BOT_API_URL >> .env
    
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install wheel
        pip install pyinstaller google-api-python-client gspread google-cloud-storage google oauth2client pandas
   
    - name: Pyinstall packaging
      run: |
        pyinstaller main.py --onefile --name cm_chat
    - name: Creating archive
      run: |
        rm -rf build watcher.spec
        find . -name \__pycache__ -exec rm -rv {} +
        tar cvf cm_chat.tar ./*     
        
    - name: Uploading prepared files
      uses: marcodallasanta/ssh-scp-deploy@v1.1.0
      with:
        local: 'cm_chat.tar'                               # Local file path - REQUIRED false - DEFAULT ./
        remote: '~/'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
        host: ${{secrets.PROD_IP}}
        port: ${{secrets.PORT}}                                      # Remote server address - REQUIRED true
        user: ${{secrets.PROD_USERNAME}}                             # Remote server user - REQUIRED true
        key: ${{secrets.SSH_TO_SERVER}}                              # Remote server private key - REQUIRED at least one of "password" or "key"
        pre_upload: echo "This will be executed before the upload!"  # Command to run via ssh before scp upload - REQUIRED false
        post_upload: tar -xvf cm_chat.tar --overwrite --dir ~/cm_chat
        ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
        scp_options: -v               
   
    - name: Post upload script
      uses: cross-the-world/ssh-pipeline@master
      env:
        WELCOME: "Welcome to the server"
      with:
        host: ${{secrets.PROD_IP}}
        port: ${{secrets.PORT}}
        user: ${{secrets.PROD_USERNAME}}
        key:  ${{secrets.SSH_TO_SERVER}}
        connect_timeout: 10s
        script: |
          cp ~/cm_chat/post_upload.sh ~
          chmod +x ~/post_upload.sh
          sudo /home/ubuntu/post_upload.sh
